apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-flask-demo-template
  title: Python Flask Demo Application
  description: Creates a Python Flask application with REST API endpoints, Docker containerization, and Kubernetes deployment
spec:
  owner: development
  type: service

  parameters:
    - title: Application Configuration
      required:
        - component_id
        - environment
        - user_name
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        environment:
          title: Environment
          type: string
          description: The environment where this component will be deployed
          enum:
            - stage
            - prod
        user_name:
          title: Application User
          type: string
          description: The user name that will be used in the application greeting (only letters, numbers, and underscores allowed)
          pattern: '^[a-zA-Z][a-zA-Z0-9_]*$'
          default: 'BackstageUser'

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{parameters.component_id}}
          app_env: ${{parameters.environment}}
          user_name: ${{parameters.user_name}}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: Python Flask Demo Application - ${{ parameters.component_id }}
        repoUrl: github.com?owner=qburst-praven&repo=${{parameters.component_id}}
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: API Documentation
        url: ${{ steps['publish'].output.remoteUrl }}/blob/main/README.md
