apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.app_name }}-ingress
  namespace: ${{ values.app_name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: ${{ values.app_name }}.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${{ values.app_name }}-service
            port:
              number: 80 