site_name: '${{ values.app_name }}'
site_description: 'Main documentation for ${{ values.app_name }}'
repo_url: https://github.com/qburst-praven/${{ values.app_name }}
edit_uri: edit/master/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting Started: 'docs/index.md'
